apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: lis689/ui:2.3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: ui
