apiVersion: v1
kind: Service
metadata:
  name: cart-mongo
  labels:
    app: cart-mongo
  namespace: micro
spec:
  ports:
    - port: 27017
  selector:
    app: cart-mongo
    tier: cart-mongo
  clusterIP: None