apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cart
  labels:
    app: cart
  namespace: micro
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
